name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.6.8 # This is the action
        with:
          heroku_api_key: ${{secrets.feab7747-e968-4a57-afa8-347fd842f737}}
          heroku_app_name: "planbot-mess"
          heroku_email: "hubert.janczaak@gmail.com"
